"""
Currency_currencyshort_alter

Revision ID: 0ee09e1c21cf
Revises: 0f30b497da7a
Create Date: 2026-02-11 14:42:29.542957

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ee09e1c21cf"
down_revision: str | Sequence[str] | None = "0f30b497da7a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "currencies",
        "currencyshort",
        existing_type=sa.VARCHAR(length=3),
        type_=sa.String(length=5),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "currencies",
        "currencyshort",
        existing_type=sa.String(length=5),
        type_=sa.VARCHAR(length=3),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
