"""FK key added

Revision ID: 2da1eb43a9de
Revises: 7867f6c62577
Create Date: 2026-02-12 09:53:45.473343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2da1eb43a9de'
down_revision: Union[str, Sequence[str], None] = '7867f6c62577'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('currency_rates', 'base_currency',
               existing_type=sa.VARCHAR(length=3),
               type_=sa.String(length=5),
               existing_nullable=False)
    op.create_foreign_key(None, 'currency_rates', 'currencies', ['base_currency'], ['currencyshort'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'currency_rates', type_='foreignkey')
    op.alter_column('currency_rates', 'base_currency',
               existing_type=sa.String(length=5),
               type_=sa.VARCHAR(length=3),
               existing_nullable=False)
    # ### end Alembic commands ###
