"""Currency models create

Revision ID: 7867f6c62577
Revises: 3fa7329a01cd
Create Date: 2026-02-12 09:05:51.323027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7867f6c62577'
down_revision: Union[str, Sequence[str], None] = '3fa7329a01cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('currencyshort', sa.String(length=5), nullable=False),
    sa.Column('currency', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('currencyshort')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('rates', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'base_currency', name='uq_currency_rates_date_base')
    )
    op.create_index('ix_currency_rates_base_date', 'currency_rates', ['base_currency', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_currency_rates_base_date', table_name='currency_rates')
    op.drop_table('currency_rates')
    op.drop_table('currencies')
    # ### end Alembic commands ###
