"""Initial alembic migration

Revision ID: aafa4688ab7a
Revises: 0ee09e1c21cf
Create Date: 2026-02-12 08:40:19.376018

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aafa4688ab7a"
down_revision: str | Sequence[str] | None = "0ee09e1c21cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("currencies")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "currencies",
        sa.Column("currencyshort", sa.VARCHAR(length=5), autoincrement=False, nullable=False),
        sa.Column("currency", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("currencyshort", name=op.f("currencies_pkey")),
    )
    # ### end Alembic commands ###
